language: haskell
ghc: '8.0.2'
sudo: false
env:
  global:
    # Travis seems to fail at setting this correctly.
    - PATH: "$HOME/.cabal/bin:$PATH"
cache:
  directories:
    - '$HOME/.cabal'
    - '$HOME/.ghc'
install:
  - cabal install --flags="make-man-page"
script:
  - make test
